services:
  postgres:
    image: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=todo1234
      - POSTGRES_DB=todo-list-db
    ports:
      - 5432:5432
