version: '3.1'

services:
  db:
    image:  postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=todo1234
      - POSTGRES_DB=todo-list-db
    secrets:
      - db_password

secrets:
  db_password:
    file: db_password.txt
